select top 100 * from sjtrade..usermenu where userid='yayuk gaks'
--update sjtrade..usermenu set userid='xxx' from sjtrade..usermenu where userid='yayuk gaks'
select top 100 * from sjtrade..usermenu where userid='MARLIANA'
--update sjtrade..usermenu set userid='YAYUK GAKS' from sjtrade..usermenu where userid='MARLIANA'
select top 100 * from sjtrade..usermenu where userid='sulis'
--update sjtrade..usermenu set userid='MARLIANA' from sjtrade..usermenu where userid='sulis'